### ISSUE TITLE
Thanks..

### ISSUE THREAD

**Issue by SunilThombare** [cjrams/astronomicalalgorithms#1]
Thanks for implementing AA+. 
Can the code for AA+ be converted to java instead of c++
Or can other planet files be embedded in this project to get an output in Android.
If yes, please help or guide.
Thanks.

**Comment by cjrams** [comment]
Yep, sorry, I did that as a test but I can add more planets easy, just tell me what you need that is already in the main [library](https://github.com/cjrams/AA) so I can expose it to java.

**Comment by SunilThombare** [comment]
Thanks for consideration. I am a novice programmer, I need this to display
the current planet details for INDIAN PANCHANG or EPHEMERIS. If you don't
have that much time, please guide me, so that I can add the remaining
planets and send you the updated version.

Thanks a lot.

**Comment by cjrams** [comment]
I did added Moon calculations, as you can see are very close to Sun one, so
other planets will be almost same. I would want to refactor .a bit to avoid
boiler plate duplication as match I can in easy way.

https://github.com/cjrams/astronomicalalgorithms/commit/9d1a1185348afac74bd65981d3c3989c41f6531f

Already added to jcenter with version 0.3.0

**Comment by SunilThombare** [comment]
I really heartily thank you a lot.. lot.. lot. Sir.
