### ISSUE TITLE
MainActivity

### ISSUE THREAD

**Issue by SunilThombare** [cjrams/astronomicalalgorithms#2]
Thanks a lot sir, 
..can I request one more thing..
..can you please add a MainActivity which calls the code..
..I tried but it gives an error "libastrononicalAlgorithms.so" not found..

Thank you so much..heartily..

**Comment by cjrams** [comment]
Added a very simple sample app to complement the readme.

https://github.com/cjrams/astronomicalalgorithms/tree/master/samples/android

**Comment by SunilThombare** [comment]
Thanks, I really appreciate your great efforts.
Thank you very very much.
